DROP DATABASE IF EXISTS LISTADEPRODUTOS;

-- DDL
CREATE DATABASE LISTADEPRODUTOS;
USE LISTADEPRODUTOS;

CREATE TABLE CATEGORIA(	
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DESC_CATEGORIA VARCHAR(30) NOT NULL
);

CREATE TABLE PRODUTO(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(60) NOT NULL,
    PRECO DECIMAL(10,2) NOT NULL,
    DESCRICAO TEXT NOT NULL,
    ID_CATEGORIA INT NULL,
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID)
);

CREATE TABLE GENEROS(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    DESC_GENERO VARCHAR(30)
);

CREATE TABLE USUARIO(
	ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	CPF VARCHAR(11) NOT NULL,
    NOME VARCHAR(35) NOT NULL,
    DT_NASCIMENTO DATE NOT NULL,
    EMAIL VARCHAR(35) NOT NULL,
    ID_GENERO INT NOT NULL,
    TELEFONE VARCHAR(9) NOT NULL,    
    FOREIGN KEY (ID_GENERO) REFERENCES GENEROS(ID)
);

